# CASS 3D Ray Tracer + LSM Configuration
# Uses RRTMGP-RT radiation and land surface model

[time]
datetime_utc=2005-07-24 10:30:00

[boundary]
swboundary=surface_lsm
swconstantz0=1
mbcbot=noslip
mbctop=freeslip
sbcbot=dirichlet
sbctop=neumann
sbot=0
stop=0
z0m = 0.075
z0h = 0.003

[land_surface]
swhomogeneous=1
swfreedrainage=1
swtilestats=0
swtilestats_column=0
switerseb=0
swwater=0
ktot=4

gD=0.0
c_veg=1.0
lai=1.5
# https://doi.org/10.1029/2024MS004658 figure 2

rs_veg_min=70
rs_soil_min=50
# https://journals.ametsoc.org/view/journals/mwre/136/11/2008mwr2524.1.xml

lambda_stable=10.0
lambda_unstable=10.0

cs_veg=0
# https://gmd.copernicus.org/articles/14/5307/2021/ section 2.1
emis_sfc=0.95
sfc_alb_dir=0.20
sfc_alb_dif=0.20

[radiation]
swradiation=rrtmgp_rt
rays_per_pixel=256
kngrid_i=64
kngrid_j=64
kngrid_k=32
emis_sfc=0.97
swlongwave=1
swshortwave=1
dt_rad=60
t_sfc=294.0
tsi_scaling=1
sfc_alb_dir=0.22
sfc_alb_dif=0.22
swclearskystats=1
swfixedsza=0
swtimedep_background=0
